### ISSUE TITLE
No errors, just no tooltip.

### ISSUE THREAD

**Issue by mayson14** [ndelvalle/ng-cooltip#11]
angular v1.4.9
does this conflict somehow with ui-bootstrap css?

I would love to use this please help!

![capture](https://cloud.githubusercontent.com/assets/8452532/16212331/c0292f04-36fb-11e6-9f41-f8b8445a0919.PNG)

copied the example from the readme to get the above.

**Comment by ndelvalle** [comment]
Hey @mayson14, sorry for the late response. It should not have conflicts with bootstrap. Did you import the css correctly?
