### ISSUE TITLE
Error: module is not defined

### ISSUE THREAD

**Issue by artattackadv** [ndelvalle/ng-cooltip#5]
I followed all the instructions, and don't use RequireJs, but recieve this error.
**ng-cooltip.js:64 Uncaught ReferenceError: module is not defined**

Same Angular version of your demo.

**Comment by gillchristian** [comment]
@artattackadv is it just a warking or you are not able to use the directive?

**Comment by lorenzo-gasperoni** [comment]
I am not able to use the directive because if i try i have an additional parse syntax error ""Error: $parse:syntax Syntax Error" about the cooltip-content tag attribute.

**Comment by gillchristian** [comment]
Can you copy both errores? I seems like they are not related.

**Comment by ndelvalle** [comment]
Hey @lorenzo-gasperoni, the errors that you mentioned are not related, the first one `ng-cooltip.js:64 Uncaught ReferenceError: module is not defined` we will upload a new version with that solved, but note that you can still use the module with this error. The second error `Error: $parse:syntax Syntax Error` must be caused for the content that you are passing to the `cooltip-content` attribute. Can you please provide with some code of how you are using the directive.

**Comment by gillchristian** [comment]
You should open a new issue for `Error: $parse:syntax Syntax Error`.

**Comment by ndelvalle** [comment]
@lorenzo-gasperoni, @artattackadv install the package, you shouldn't have this `Uncaught ReferenceError: module is not defined` error again.
If you still having the `Error: $parse:syntax Syntax` error, feel free to open a new issue :+1: .
